### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by mikeebowen** [yuenm18/ooxml-viewer-vscode#12]
I think it would be a good enhancement to add [travis-ci](https://travis-ci.org/) to the README.md

**Comment by yuenm18** [comment]
Do we need to add travis-ci if we already are using azure devops pipelines?

**Comment by mikeebowen** [comment]
I suppose we don't need it, but the test coverage is good, so I think it's a positive thing to call out.

**Comment by yuenm18** [comment]
Ah I see
