### ISSUE TITLE
ChineseCharProblems

### ISSUE THREAD

**Issue by vincentyang116** [yuenm18/ooxml-viewer-vscode#15]
Hi, thanks a lot for your work!
I have mat a problem when processing Chinese document, parsing and display are working fine, but after saving the edit, all Chinese char including font name will saved as some unknown char.
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/38676561/108270868-f8f33700-71aa-11eb-951b-ca26f2b123cb.png">
Is this some bug of the plugins or am I missing some necessary lib, or something wrong with my settings. I'm using macOs.
Thanks again.

**Comment by yuenm18** [comment]
Fixed in version 1.0.2

**Comment by vincentyang116** [comment]
It's worked, thanks.
