### ISSUE TITLE
Analyzing multiple document

### ISSUE THREAD

**Issue by onurkanbakirci** [yuenm18/ooxml-viewer-vscode#34]
When i try to see multiple word document's `document.xml` file in order to compare these files and detect differences between `.xml` tags, plugin isn't allow to me. It's working like a toggle button. When i try to analyze another word document `.xml` files at the same time, old document's `.xml` files is closed by plugin. So, is there any way to visualize **different** two or more `.xml` file at the same time?

**Comment by mikeebowen** [comment]
Hi @onurkanbakirci ,
This would be a significant change to how the TreeView and comparing with previous versions work and would involve a lot of work and I don't know if there is bandwidth for it right now, but pull requests are always appreciated if you have time to work on this.

For a work around you could save the two xml files you want to compare to a folder on your system, then open that folder and compare the files with VS Code. It's not elegant, but there's no way to compare from the extension.
