### ISSUE TITLE
Compare with previous no longer works with pptx

### ISSUE THREAD

**Issue by pastafari** [yuenm18/ooxml-viewer-vscode#36]
Hi and thank you for building and maintaining this plugin. It is very useful <3 

I have been using the "Compare With Previous" to see what changes in xml files when I make changes to a PowerPoint presentation. This stopped working completely in recent times. Meaning that I no longer see diffs in the file (no yellow asterisk, etc.). Perhaps it has something to do with #28 

System details:
OS X version: `Big Sur 11.6.6` 
VS Code version: `1.69.2` 
extension version: `v1.2.2` 

https://user-images.githubusercontent.com/193407/182645271-ae88d00b-4f45-40b9-9bf3-c097603c0edf.mov

Sorry for the low-res video, I had to compress it. 

Let me know if I can provide any other info to help debug. And thanks again.

**Comment by mikeebowen** [comment]
Hi @pastafari ,

I tried to reproduce with a pptx file, but I see the Compare with Previous functionality and asterisks on the changed files. Are you seeing this with Word or Excel? Also, maybe you pressed ctrl + s, so I didn't see it in the video, but I didn't see you save the file (the versions are only compared on save).

It may have no effect but re-installing the extension and restarting VS Code might help.

**Comment by pastafari** [comment]
Hi @mikeebowen - thanks for the prompt reply. 

For clarity, I did Save the PPTX file after editing it in PowerPoint, that did not trigger a refresh in VSCode.

I tried re-installing VS Code and the extension, that did not work either.

Rolling back to an older version of the extension `v1.2.0` made it work (partially). 
- the first change made via PowerPoint would reflect in VSCode
- but subsequent changes were not being picked up. 

Ideally, I'd love to see the diff being updated every time I hit Save on PowerPoint.

I suspect there's something going on with the FileSystem being cached, and onSave signals from the external program not leading to a refresh in the plugin. 

fwiw, are you also on OSX?

**Comment by adamshakhabov** [comment]
@pastafari, I had such issue. Unfortunattely, I don't remember what exactly helped me, but I think the cause of the issue was the _long_ file path. I fixed this by moving my file, eg. from `c:\folder\sub-folder\sub-folder\test.pptx` to `c:\folder\test.pptx`.
