### ISSUE TITLE
Comments not preserved in XML parts

### ISSUE THREAD

**Issue by tomjebo** [yuenm18/ooxml-viewer-vscode#37]
I'm using version `1.2.2` on Windows 10. When I edit a part of an OOXML package and add a comment liek the following: 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<calcChain xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <!-- <c r="C1" i="1" l="1"/> -->
  <c r="C1" i="1" l="1"/>
</calcChain>
```

Upon save (`Ctrl-S` in VS Code), the part is saved but the commented line disappears. 

Is it possible to preserve the comment?

**Comment by mikeebowen** [comment]
This should be a small change. We can add the option to preserve comments in setttings.json.

**Comment by tomjebo** [comment]
Awesome! Thanks @mikeebowen
