### ISSUE TITLE
Open OOXML Package in New Tab

### ISSUE THREAD

**Issue by adamshakhabov** [yuenm18/ooxml-viewer-vscode#40]
Not sure, but it could be related to issue [#13](https://github.com/yuenm18/ooxml-viewer-vscode/issues/34).

It would be great to be able to work with multiple documents in _separate tabs_ _within the same Visual Studio Code window_. For example, when a user right-clicks, there should be an additional option of "Open OOXML Package in New Tab."

Currently, as a workaround, I have to place the files in _different_ folders and open a new Visual Studio Code window for the second file.

**Comment by yuenm18** [comment]
I think we'll want to go with allowing multiple documents in the ooxml viewer like in #13 so we can reuse the TreeView.  I'll take a look at this soon to try see how hard it will be to implement
