### ISSUE TITLE
Plugin stopped working on VS Code 1.78

### ISSUE THREAD

**Issue by rychoo2** [yuenm18/ooxml-viewer-vscode#42]
The plugin no longer works since VSCode 1.78. Clicking on "Open OOXML Package" doesn't do anything.
Downgrading VS Code to 1.77.3 makes it work again.
Please help.

**Comment by mikeebowen** [comment]
Hi @rychoo2 
Are there any errors or other messages? Have your tried clicking on a different file then trying to right click and "Open OOXML Package" again? Sometimes VS Code gets in a weird state that can be fixed by clicking on a different file.

**Comment by rychoo2** [comment]
I don't see any errors or messages. Does this plugin have a log file somewhere so I can check for you?
Trying it on a different file doesn't help. Tried rebooting or reinstalling the plugin but still the same. Everything works OK after downgrading VS code. 
Also, the issue happens to other colleagues in my team so should be easy to reproduce. We use Windows.

**Comment by yuenm18** [comment]
I tried reproducing this issue but it's working for me.  This is my system/vscode info:

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

The extension doesn't have any logs at the moment

**Comment by rychoo2** [comment]
Thanks @yuenm18 and @mikeebowen for looking into this. After you couldn't reproduce this in the meantime I went ahead and hard reinstalled VS Code. This appears to have solved the problem for us. 

Thanks for adding the logging, will be helpful next time.
