### ISSUE TITLE
Trouble installing the extension

### ISSUE THREAD

**Issue by james-alonso** [yuenm18/ooxml-viewer-vscode#6]
Thanks for making this!  I tried to install in VS Code, and I don't seem to be able to get it to work.

When I install, I get a menu in the left sidebar called "OOXML Viewer" but I don't see the menu for "OOXML Editor" that I see in your gif demo.

Here's what I see:  <img width="902" alt="Screen Shot 2020-10-10 at 4 51 49 PM" src="https://user-images.githubusercontent.com/616449/95667293-e7bd5e00-0b18-11eb-9cf0-acb0e6a35461.png">

Is there something else I need to do to make this work?  Would love to be able to use this!

Thank you!

**Comment by yuenm18** [comment]
You should get the menu option to "View Contents" when you right click on your docx file. I hope this helps!

**Comment by yuenm18** [comment]
Yea within vscode.  Try to open the folder containing the docx file in vscode and right click on the docx file that shows up in the panel labeled by the folder's name.

**Comment by hugomallinson** [comment]
This only works when you open a folder containing an OOXML file. If you open the file directly "View Contents" doesn't show up in the context menu. This would be a nice feature.
