### ISSUE TITLE
Parsing XML doesn't work properly

### ISSUE THREAD

**Issue by shumi2nd** [yuenm18/ooxml-viewer-vscode#9]
Hello, I recently started to learn Office Open XML, I installed this plugin in VS Code, but there seem to be some problems when I use it.

1. When I right-click on a document and select 'View Contents', no load notification appears, but the' OOXML Viewer 'window still correctly displays the uncompressed file directory, but when I click on the'.xml 'file, it appears unsaved, even though it has been formatted in the edit area.
2. I tried to modify and save the document in Office, and after switching to VS Code, I did not see the load notice, nor did the asterisk of file modification appear in the "OOXML Viewer" window.

environment:win10_1803+vscode_1.52.1+Microsoftoffice365/WPSoffice
My English is not well, so you can watch [my video demo](https://streamja.com/rLKQe).If I have improper operation, please tell me, thank you!

**Comment by yuenm18** [comment]
Those features will be available after version 1.0.0 is released. The current version (0.0.1) only can view the files.  I'm working on some code cleanup right now and testing before publishing version 1.0.0. I should be done in a couple of days.

**Comment by shumi2nd** [comment]
> Those features will be available after version 1.0.0 is released. The current version (0.0.1) only can view the files. I'm working on some code cleanup right now and testing before publishing version 1.0.0. I should be done in a couple of days.

🎉👏Can't wait to taste it, and the description [here](url
[text_3.txt](https://github.com/yuenm18/ooxml-viewer-vscode/files/5779339/text_3.txt)
) should be 'PPTX'?

**Comment by shumi2nd** [comment]
> Those features will be available after version 1.0.0 is released. The current version (0.0.1) only can view the files. I'm working on some code cleanup right now and testing before publishing version 1.0.0. I should be done in a couple of days.
🎉👏Can't wait to taste it, and the description [here](https://github.com/yuenm18/ooxml-viewer-vscode#diff-adding-a-slide-to-a-docx-file) should be 'PPTX'。

**Comment by mikeebowen** [comment]
Hi @shumi2nd please feel free to submit a pull request 😀
